version: '3.4'

services:
  api.multiple:
    image: multipleservice
    hostname: api.multiple
    ports:
    - 7009:80
    build:
      context: .
      dockerfile: MultipleService/Dockerfile

  api.plus:
      image: plusservice
      hostname: api.plus
      ports:
      - 7008:80
      build:
        context: .
        dockerfile: PlusService/Dockerfile

  api.gateway:
      image: gateway
      hostname: api.gateway
      ports:
      - 7000:80
      build:
        context: .
        dockerfile: Gateway/Dockerfile