version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
    - 8080:15672
    - 5672:5672

  queue.listener:
    image: queuelistener
    hostname: queue.listener
    ports:
    - 7001:80
    build:
      context: .
      dockerfile: QueueListener/Dockerfile
    depends_on:
      - rabbitmq

  # queue.publisher:
  #   image: queuepublisher
  #   hostname: queue.publisher
  #   ports:
  #   - 7002:80
  #   build:
  #     context: .
  #     dockerfile: QueuePublisher/Dockerfile
  #   depends_on:
  #     - rabbitmq

  api.multiple:
    image: multipleservice
    hostname: api.multiple
    ports:
    - 7009:80
    build:
      context: .
      dockerfile: MultipleService/Dockerfile
    depends_on:
      - rabbitmq

  api.plus:
      image: plusservice
      hostname: api.plus
      ports:
      - 7008:80
      build:
        context: .
        dockerfile: PlusService/Dockerfile

  api.gateway:
      image: gateway
      hostname: api.gateway
      ports:
      - 7000:80
      build:
        context: .
        dockerfile: Gateway/Dockerfile